name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          args: >
            -Dsonar.projectKey=ratanram242_devops-demo
            -Dsonar.organization=ratanram242
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run app
        run: node index.js
        
      - name: Notify Jira on Failure
        if: failure()
        run: |
          curl -X POST "https://api-private.atlassian.com/automation/webhooks/jira/a/59d40bfa-8f92-4f29-97a6-315c2444bac8/019d33c7-73f3-75f7-90e5-cb7ad647b38d"

      - name: Force Fail
        run: exit 1
