name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=ratanram242_devops-demo
            -Dsonar.organization=ratanram242
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run app
        run: node index.js
